catalog_name: mlops_dev
schema_name: diabetes

seed: 42
test_size: 0.2

num_features:
  - BMI
  - MentHlth
  - PhysHlth

cat_features:
  - HighBP
  - HighChol
  - CholCheck
  - Smoker
  - Stroke
  - HeartDiseaseorAttack
  - PhysActivity
  - Fruits
  - Veggies
  - HvyAlcoholConsump
  - AnyHealthcare
  - NoDocbcCost
  - GenHlth
  - DiffWalk
  - Sex
  - Age
  - Education
  - Income

target: Diabetes_012

model_parameters:
  obj_fn: "multi:softmax"
  n_estimators: 1000
  max_depth: 6
  learning_rate: 0.01
